# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

  inhibit_all_warnings!
  use_frameworks!

def all_pods
    pod 'RealmSwift'
  	pod 'SwiftLint'
  	pod 'IQKeyboardManagerSwift'
end
 

target 'Contacts App' do
	all_pods
end

target 'Contacts AppTests' do
	all_pods
end
