# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calendar App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Calendar App
  pod 'SwiftLint'
  pod 'IQKeyboardManagerSwift'

end
